### ISSUE TITLE
请问重写了什么

### ISSUE THREAD

**Issue by ganxiaozhe** [accPenguin/Cracking_Hash_headers#3]
> 但我觉得这个写的不好，我要重写一下：）

比较好奇代码是哪部分被重写了. - -

**Comment by accPenguin** [comment]
有没有可能，就是说，我忘传代码了
还是看原博主吧，他比较专业：）

**Comment by ganxiaozhe** [comment]
> 有没有可能，就是说，我忘传代码了 还是看原博主吧，他比较专业：）

嗯，有没有可能原作者就是我...

Anyway, 顺颂近祺
